[package]
name = "todo-list-web"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
rusqlite = "0.26.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "todo-list-web"
path = "main.rs"